In [42]:
import numpy as np
import scipy.linalg as LAS

In [49]:
def insert_T_matrix():
  print("Please insert 3x4 matrix:")

  matrix = np.zeros((3, 4))

  # Ucitavanje matrice
  for i in range(3):
    for j in range(4):
      x = int(input())
      matrix[i][j] = x

  T0 = np.zeros((3, 3))
  # Izdvajanje matrice T0
  for i in range(3):
    for j in range(3):
      T0[i][j] = matrix[i][j]

  # Ukoliko je det(T0) < 0 treba
  # celu matricu T pomnoziti sa -1
  if LA.det(T0) < 0:
    for i in range(3):
      for j in range(4):
        matrix[i][j] = -matrix[i][j]

  return matrix

#T = insert_T_matrix()

#T = [[5, -23, 3, -15], [0, -1, 5, 21], [0, -1, 0, 1]]
T = [[5, -19, 3, -9], [0, -1, 5, 21], [0, -1, 0, 1]]

In [52]:
def find_A_and_K_paremeter(T):

  T0 = np.zeros((3, 3))

  # Izdvaja se T0
  for i in range(3):
    for j in range(3):
      T0[i][j] = T[i][j]

  col = [T[0][3], T[1][3], T[2][3]]

  # Resava se sistem -T0*C = col
  C = LAS.solve(-T0, col)

  # Radi se Q, R dekompozicija od inv(T0)
  Q, R = LAS.qr(LAS.inv(T0))

  Q[:][1] = -Q[:][1]
  Q[:][2] = -Q[:][2]

  # Ukoliko je i-ti dijagonalni elemenat
  # matrice R manji od 0 treba pomnoziti
  # i-tu vrstu matrice R i i-tu kolonu
  # matrice Q sa -1 
  for i in range(3):
    for j in range(3):
      if i == j:
        if R[i][j] < 0:
          Q[:][i] = -1*Q[:][i]
          R[i][:] = -1*R[i][:]

  K = LAS.inv(R)
  A = np.transpose(Q)

  for i in range(3):
    for j in range(3):
      K[i][j] /= K[2][2]

  return K, A, C

K, A, C = find_A_and_K_paremeter(T)

print("Matrix K is:")
print(K)
print()
print()
print("Matrix A is:")
print(A)
print()
print()
print("Vector C is:")
print(C)

Matrix K is:
[[ 5.  3. 19.]
 [ 0.  5.  1.]
 [ 0.  0.  1.]]


Matrix A is:
[[ 1.  0. -0.]
 [ 0.  0.  1.]
 [ 0. -1. -0.]]


Vector C is:
[ 8.  1. -4.]


In [48]:
def DLT_camera(originals, projections):
  if(len(originals) < 4 or len(projections) < 6 or len(originals) != len(projections)):
    print("Losi argumenti funkcije!")
    return None

  n = len(originals)

  matrix = np.array([], dtype=np.float32).reshape(0, 12)

  for i in range(0, n):
    point1 = originals[i]
    point2 = projections[i]

    tmp = np.array([[0, 0, 0, 0,     -point2[2]*point1[0], -point2[2]*point1[1], -point2[2]*point1[2], -point2[2]*point1[3],            point2[1]*point1[0], point2[1]*point1[1], point2[1]*point1[2], point2[1]*point1[3]], 
                    [point2[2]*point1[0], point2[2]*point1[1], point2[2]*point1[2], point2[2]*point1[3],          0, 0, 0, 0,          -point2[0]*point1[0], -point2[0]*point1[1], -point2[0]*point1[2], -point2[0]*point1[3]]])

    matrix = np.concatenate((matrix, tmp), axis=0)

  SVD = np.linalg.svd(matrix, compute_uv=True)
  T = SVD[2][-1].reshape(3, 4)

  return T/(T[0][0])

#originals = [[460, 280, 250, 1], [50, 380, 350, 1], [470, 500, 100, 1], [380, 630, 550, 1], [330, 290, 0, 1], [580, 0, 130, 1]]
#projections = [[288, 251, 1], [79, 510, 1], [470, 440, 1], [520, 590, 1], [365, 388, 1], [365, 20, 1]]

originals = [[460, 280, 250, 1], [50, 380, 350, 1], [470, 380, 100, 1], [380, 630, 450, 1], [270, 290, 0, 1], [580, 0, 130, 1]]
projections = [[288, 251, 1], [79, 510, 1], [470, 440, 1], [520, 590, 1], [365, 388, 1], [365, 20, 1]]


T = DLT_camera(originals, projections)
print("Matrica T je:")
for i in range(3):
  print(T[i])

Matrica T je:
[   1.           -1.08496482    3.22926156 -880.05413699]
[ 2.14671162e+00 -1.84357560e-01  2.58960820e+00 -1.57480233e+03]
[ 4.77690501e-03 -1.81572964e-03  7.02580605e-03 -3.30025526e+00]
