In [53]:
import numpy as np
import numpy.linalg as LA

In [75]:
def insert_T_matrix():
  print("Please insert 3x4 matrix:")

  matrix = np.zeros((3, 4))

  # Ucitavanje matrice
  for i in range(3):
    for j in range(4):
      x = int(input())
      matrix[i][j] = x

  T0 = np.zeros((3, 3))
  # Izdvajanje matrice T0
  for i in range(3):
    for j in range(3):
      T0[i][j] = matrix[i][j]

  # Ukoliko je det(T0) < 0 treba
  # celu matricu T pomnoziti sa -1
  if LA.det(T0) < 0:
    for i in range(3):
      for j in range(4):
        matrix[i][j] = -matrix[i][j]

  return matrix

T = insert_T_matrix()

Please insert 3x4 matrix:
5
-23
3
-15
0
-1
5
21
0
-1
0
1


In [78]:
def find_C_parameter(T):

  T0 = np.zeros((3, 3))

  # Izdvaja se matrica T0
  for i in range(3):
    for j in range(3):
      T0[i][j] = T[i][j]

  # izdavaje se poslednja kolona iz T
  col = [T[0][3], T[1][3], T[2][3]]

  # Resava se sistem -T0*C = col
  C = LA.solve(-T0, col)

  return C

find_C_parameter(T)

array([10.,  1., -4.])

In [79]:
def find_A_and_K_paremeter(T):

  T0 = np.zeros((3, 3))

  # Izdvaja se T0
  for i in range(3):
    for j in range(3):
      T0[i][j] = T[i][j]

  # Radi se Q, R dekompozicija od inv(T0)
  Q, R = LA.qr(LA.inv(T0))

  #Q = np.column_stack([Q[: i] if R[i, i] > 0 else -1*Q[:, i] for i in range(len(Q))])
  #R = np.array([R[i] if R[i, i] > 0 else -1*R[i] for i in range(len(R))])

  print("Matrix Q:")
  print(Q)

  print()
  print()

  print("Matrix R:")
  print(R)
  print()
  print()

  # Ukoliko je i-ti dijagonalni elemenat
  # matrice R manji od 0 treba pomnoziti
  # i-tu vrstu matrice R i i-tu kolonu
  # matrice Q sa -1 
  for i in range(3):
    for j in range(3):
      if i == j:
        if R[i][j] < 0:
          Q[:][i] = -1*Q[:][i]
          R[i][:] = -1*R[i][:]
          # Ovo moze biti veliki problem
          #Q[:][i-1] = -Q[:][i-1]

  K = LA.inv(R)
  A = np.transpose(Q)

  for i in range(3):
    for j in range(3):
      K[i][j] /= K[2][2]

  return K, A

K, A = find_A_and_K_paremeter(T)

print("Matrix K is:")
print(K)
print()
print()
print("Matrix A is:")
print(A)
print()
print()
print(K @ A)

Matrix Q:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


Matrix R:
[[ 0.2  -0.12 -4.48]
 [ 0.    0.2  -0.2 ]
 [ 0.    0.   -1.  ]]


Matrix K is:
[[ 5.  3. 23.]
 [ 0.  5.  1.]
 [ 0.  0.  1.]]


Matrix A is:
[[ 1.  0. -0.]
 [ 0.  0. -1.]
 [ 0.  1. -0.]]


[[ 5. 23. -3.]
 [ 0.  1. -5.]
 [ 0.  1.  0.]]
